### ISSUE TITLE
Cannot install addon with Firefox 57 (but works fine with 59)

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings-devtools#17]
With stable 57

![screenshot from 2018-01-12 18-09-45](https://user-images.githubusercontent.com/546692/34886602-cc017c48-f7c3-11e7-9a3e-80066816160c.png)

With Nightly 59

![screenshot from 2018-01-12 18-08-20](https://user-images.githubusercontent.com/546692/34886576-b4a0bfaa-f7c3-11e7-93d4-9e22b142b217.png)

**Comment by leplatrem** [comment]
Apparently the way to do it would be webextension+bundle

**Comment by mostlygeek** [comment]
more options / info:

* there are plans to only support the webextension API
* The bundle approach, allows new APIs to be bundled with and shipped with the webextension XPI.  

The bundle approach, AFIAK is a way to propose new APIs and also makes it easier to deprecate and ultimately remove support for legacy extensions.

**Comment by leplatrem** [comment]
The addon now uses Browser Extension Experiments. Closing :)
