### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/remote-settings-devtools#31]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/remote-settings-devtools/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by leplatrem** [comment]
Thanks!

**Comment by leplatrem** [comment]
>  Please make that change (documentation).

@moz-hwine It seems like I don't have the permisssions to do access settings

**Comment by moz-hwine** [comment]
Settings are correct, and wiki disabled (not used).
