### ISSUE TITLE
Broken UI on dark theme

### ISSUE THREAD

**Issue by flodolo** [mozilla/remote-settings-devtools#36]
I'm using Nightly (70) on macOS with dark theme, and there's basically no UI

<img width="1226" alt="Schermata 2019-08-29 alle 11 56 18" src="https://user-images.githubusercontent.com/3644868/63930708-26e33980-ca54-11e9-87fc-338307632bc8.png">

**Comment by leplatrem** [comment]
Oh, thanks! We should use more CSS variables I guess :/

**Comment by flodolo** [comment]
It looks like it's actually using a variable for the font color, the problem might be with the rest of the UI.

```
body {
    color: var(--in-content-text-color);
}
```

Setting black on this at least let me see the text.
